# This file is used to define the CI workflow for the project.  

name: CI Go Web App

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go 1.22.5
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.5'

      - name: build
        run: go build -o go-web-app

      - name: Test
        run: go test ./..

  CodeQuality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.0

  Docker-push:
    runs-on: ubuntu-latest
    needs: [build, CodeQuality]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOEKN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.run_id }}

  update-new-tag-helm:
    runs-on: ubuntu-latest
    needs: Docker-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update Helm chart with new image tag
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "shreyasdevarkar007@gmail.com"
          git config --local user.name "shreyasd-git"
          git add helm/go-web-app-chart/values.yaml
          git commit -m "Update Helm chart with new image tag"
          git push origin main


    
